/**
 * Configuration loader for zylos-pages
 *
 * Loads config from ~/zylos/components/pages/config.json
 * with hot-reload support via file watcher.
 */

import fs from 'fs';
import path from 'path';

const HOME = process.env.HOME;
export const DATA_DIR = process.env.PAGES_DATA_DIR || path.join(HOME, 'zylos/components/pages');
export const CONFIG_PATH = path.join(DATA_DIR, 'config.json');

// Default configuration
export const DEFAULT_CONFIG = {
  enabled: true,
  port: 3462,
  publicBaseUrl: null,
  contentDir: path.join(HOME, 'zylos/http/public/pages'),
  theme: {
    colorScheme: 'auto',
    codeTheme: 'github-dark',
  },
  cache: {
    enabled: true,
    maxEntries: 200,
    ttlSeconds: 3600,
  },
  toc: {
    enabled: true,
    minHeadings: 3,
  },
  auth: {
    password: null,
  },
  security: {
    allowRawHtml: false,
    maxFileSizeBytes: 1048576,
    renderTimeoutMs: 5000,
  },
  rateLimit: {
    windowMs: 60000,
    max: 60,
  },
  proxy: {
    trust: 'loopback',
  },
  sharing: {
    enabled: true,
    // The keyring must live outside pages.db and is never generated by the
    // service itself. The install/upgrade hooks set a default path here and
    // create the keyring when custody was never configured; a configured but
    // missing keyring still fails closed (see hooks/ensure-share-password-keyring.js).
    passwordKeyFile: null,
    passwordRateLimit: {
      windowMs: 60000,
      tokenMax: 8,
      ipMax: 24,
    },
  },
  attachments: {
    maxFileSizeBytes: 5 * 1024 * 1024,
    // Both of the following bound share-link writers only; a logged-in owner is
    // not rationed. See src/routes/attachment-api.js.
    maxPerItem: 50,
    maxArtifactBytes: 100 * 1024 * 1024,
    shareWriteRateLimit: {
      windowMs: 60000,
      max: 12,
      ipMax: 30,
    },
  },
  state: {
    // Share visitors are bounded independently from the authenticated owner.
    // 1 MiB is deliberately reachable below 50 x 64 KiB values, unlike the
    // attachment ceiling, so both limits protect a real state shape.
    maxKeysPerPage: 50,
    maxPageBytes: 1024 * 1024,
    shareWriteRateLimit: {
      windowMs: 60000,
      max: 12,
      ipMax: 30,
    },
  },
  externalFiles: {
    enabled: true,
    allowedSources: {
      recruit: path.join(HOME, 'zylos/components/recruit'),
    },
  },
};

let config = null;
let configWatcher = null;

/**
 * Load configuration from file
 * @returns {Object} Configuration object
 */
export function loadConfig() {
  try {
    if (fs.existsSync(CONFIG_PATH)) {
      const content = fs.readFileSync(CONFIG_PATH, 'utf8');
      const fileConfig = JSON.parse(content);
      config = deepMerge(DEFAULT_CONFIG, fileConfig);
    } else {
      console.warn(`[pages] Config file not found: ${CONFIG_PATH}`);
      config = { ...DEFAULT_CONFIG };
    }
  } catch (err) {
    console.error(`[pages] Failed to load config: ${err.message}`);
    config = { ...DEFAULT_CONFIG };
  }
  return config;
}

/**
 * Get current configuration
 * @returns {Object} Configuration object
 */
export function getConfig() {
  if (!config) {
    loadConfig();
  }
  // Allow env var override for port
  if (process.env.PAGES_PORT) {
    config.port = parseInt(process.env.PAGES_PORT, 10);
  }

  return config;
}

/**
 * Start watching config file for changes
 * @param {Function} onChange - Callback when config changes
 */
export function watchConfig(onChange) {
  if (configWatcher) {
    configWatcher.close();
  }

  if (fs.existsSync(CONFIG_PATH)) {
    configWatcher = fs.watch(CONFIG_PATH, (eventType) => {
      if (eventType === 'change') {
        console.log('[pages] Config file changed, reloading...');
        loadConfig();
        if (onChange) {
          onChange(config);
        }
      }
    });
  }
}

/**
 * Stop watching config file
 */
export function stopWatching() {
  if (configWatcher) {
    configWatcher.close();
    configWatcher = null;
  }
}

function deepMerge(target, source) {
  const result = { ...target };
  for (const key of Object.keys(source)) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])
        && target[key] && typeof target[key] === 'object') {
      result[key] = deepMerge(target[key], source[key]);
    } else {
      result[key] = source[key];
    }
  }
  return result;
}
