// HTML sanitization and frontmatter escaping (P0-2)

import sanitizeHtml from 'sanitize-html';

const ESCAPE_MAP = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

/**
 * HTML-escape a string for safe insertion into HTML attributes/content.
 */
export function escapeHtml(str) {
  if (typeof str !== 'string') return '';
  return str.replace(/[&<>"']/g, (ch) => ESCAPE_MAP[ch]);
}

/**
 * Sanitize rendered HTML to remove dangerous elements.
 * When allowRawHtml is false (default), strips all HTML tags from markdown source.
 * When true, applies a restrictive allowlist.
 */
export function sanitizeRenderedHtml(html, allowRawHtml = false) {
  if (!allowRawHtml) {
    // Strip everything that isn't generated by our renderer
    return sanitizeHtml(html, {
      allowedTags: sanitizeHtml.defaults.allowedTags.concat([
        'img', 'details', 'summary', 'pre', 'code', 'span',
        'table', 'thead', 'tbody', 'tr', 'th', 'td',
        'input', 'del', 's', 'sup', 'sub', 'hr',
      ]),
      allowedAttributes: {
        ...sanitizeHtml.defaults.allowedAttributes,
        code: ['class'],
        span: ['class', 'style'],
        pre: ['class', 'style'],
        img: ['src', 'alt', 'title', 'width', 'height'],
        input: ['type', 'checked', 'disabled'],
        th: ['align'],
        td: ['align'],
        a: ['href', 'title', 'target', 'rel'],
      },
      allowedSchemes: ['http', 'https', 'mailto'],
      // Disallow javascript: and data: URIs
      disallowedTagsMode: 'discard',
    });
  }

  // Even with raw HTML enabled, still sanitize dangerous elements
  return sanitizeHtml(html, {
    allowedTags: false, // allow all tags
    allowedAttributes: false, // allow all attributes
    disallowedTagsMode: 'discard',
    exclusiveFilter: (frame) => {
      // Remove script, iframe, object, embed, form
      return ['script', 'iframe', 'object', 'embed', 'form'].includes(frame.tag);
    },
  });
}

/**
 * Escape all string values in a frontmatter object for safe HTML output.
 */
export function escapeFrontmatter(data) {
  const escaped = {};
  for (const [key, value] of Object.entries(data)) {
    if (typeof value === 'string') {
      escaped[key] = escapeHtml(value);
    } else if (Array.isArray(value)) {
      escaped[key] = value.map(v => typeof v === 'string' ? escapeHtml(v) : v);
    } else {
      escaped[key] = value;
    }
  }
  return escaped;
}
